### ISSUE TITLE
Singularity container creation

### ISSUE THREAD

**Issue by KristinaGagalova** [bcgsc/ntSynt#43]
Hi Lauren, 

Thank you for working on such a useful tool; I already use it.

Can we create a singularity container since it is easy for us to use on the HPC? I can also create my one (see singularity container creation from conda [HERE](https://stackoverflow.com/questions/54678805/containerize-a-conda-environment-in-a-singularity-container)), but I thought you might want to keep the BCGSC images more officially. 
So far, Conda is not the best way to manage software because of potential conflicts; making a separate image for each tool is more convenient through singularity. But that's my personal user experience :)

Cheers
Kristina

**Comment by lcoombe** [comment]
Hi Kristina,

I'm really glad to hear that you're finding ntSynt useful!

For singularity - have you given the Quay.io biocontainer a try? (https://quay.io/repository/biocontainers/ntsynt?tab=tags) Those are the docker images that are automatically generated/updated when there is a new build or version for the corresponding recipe.

Let me know if that would work for you, otherwise I can look into alternatives on our end.

Thanks!
Lauren

**Comment by KristinaGagalova** [comment]
Hi Lauren, 
That's perfect! Thank you for sharing, I will us that one

**Comment by lcoombe** [comment]
Awesome! Glad that works for you - it's so handy that they make those docker images automatically for us!

Let me know if you have any other ntSynt questions!
