### ISSUE TITLE
Problem with arrange() from the `plot_synteny_blocks_gggenomes.R` script 

### ISSUE THREAD

**Issue by jgplanta** [bcgsc/ntSynt#57]
Hi Lauren,

Thanks for this program. I have been successful with running the synteny part but I did encounter a problem with visualization using the `plot_synteny_blocks_gggenomes.R` script:

```
$ Rscript plot_synteny_blocks_gggenomes.R -s *.sequence_lengths.tsv -l *.links.tsv --scale 1e7
Loading required package: ggplot2

Attaching package: ‘gggenomes’

The following object is masked from ‘package:graphics’:

    layout

Error in arrange(., factor(bin_id, levels = input_order), factor(seq_id,  :
  could not find function "arrange"
Calls: %>%
Execution halted
```

Thanks.

Joe

**Comment by lcoombe** [comment]
Hi Joe,

Glad to hear that the synteny detection step worked well for you! We are working on a more robust synteny visualization tool that should be released in the coming months so keep an eye out for that - I hope that will have less hiccups than this example R script that we currently have.

Could you try adding `library(dplyr)` to the script? `arrange` should be available in that library - I may just have missed including that one because it is often already loaded in my environments.

Thank you for your interest in ntSynt!
Lauren

**Comment by jgplanta** [comment]
Thanks, Lauren. I also added `library(ggthemr)` to the script and that made it work.

-Joe

**Comment by lcoombe** [comment]
Thanks for that update - glad you got it working! We’ll make a note of that, and will let you know when our new visualization tool is available :)
